app = "rachel-vector-memory"
primary_region = "dfw"

[build]

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 1
  processes = ["web"]

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1

[processes]
  web = "gunicorn app:app --bind 0.0.0.0:5000"
